apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgateway
  namespace: aks-istio-ingress
spec:
  selector:
    istio: aks-istio-ingressgateway-external  
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ print "*." .Values.WEBAPP_DOMAIN | quote }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingress-tls
    hosts:
    - {{ print "*." .Values.WEBAPP_DOMAIN | quote }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  default-virtualservice
  namespace: aks-istio-ingress
spec:
  hosts:
  -  {{ print "*." .Values.WEBAPP_DOMAIN | quote }}
  gateways:
  -  aks-istio-ingress/istio-ingressgateway
  http:
  - match:
    - uri:
        exact: {{ print .Values.CERT.SHOP_URL_CHALLENGE_PATH | quote }}
    route:
    - destination:
        host: {{ print .Values.CERT.SHOP_URL_SERVICE_NAME }}
        port:
          number: 8089
  - match:
    - uri:
        exact: {{ print .Values.CERT.IDENTITY_URL_CHALLENGE_PATH | quote }}
    route:
    - destination:
        host: {{ print .Values.CERT.IDENTITY_URL_SERVICE_NAME }}
        port:
          number: 8089          
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: default-backend-svc
        port:
          number: 80