apiVersion: v1
kind: Secret
metadata:
  name: eshop-eventbus-secrets
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  RABBITMQ_CONNECTION_STRING: {{ print "amqp://" .Values.EVENTBUS.USER ":" .Values.EVENTBUS.PASSWORD "@eventbus." .Values.NAMESPACES.INFRA ".svc.cluster.local:" .Values.EVENTBUS.PORT | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: eshop-eventbus-secrets
  namespace: {{ .Values.NAMESPACES.INFRA  }}
type: Opaque
data:
  RABBITMQ_DEFAULT_PASS: {{ .Values.EVENTBUS.PASSWORD | b64enc }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: eventbus 
  namespace: {{ .Values.NAMESPACES.INFRA }}
  labels:
    app: {{ .Chart.Name }}
    service: eventbus 
spec:
  replicas: 1
  selector:
    matchLabels:
      service: eventbus 
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: eventbus 
    spec:
      nodeSelector:
        App: eshop    
      containers:
      - name: rabbitmq
        image: library/rabbitmq:3
        imagePullPolicy: Always
        ports:
          - name: rabbitmq-http
            containerPort: {{ .Values.EVENTBUS.PORT }}
            protocol: TCP
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: {{ .Values.EVENTBUS.USER | quote }}
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: eshop-eventbus-secrets
                key:  RABBITMQ_DEFAULT_PASS
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: eventbus 
  namespace: {{ .Values.NAMESPACES.INFRA }}
  labels:
    app: {{ .Chart.Name }}
    service: eventbus 
spec:
  type: ClusterIP
  ports:
    - name: eventbus 
      port: {{ .Values.EVENTBUS.PORT }}
      targetPort: rabbitmq-http
  selector:
    service: eventbus 
