apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.NAMESPACES.APP }}
  labels:
    istio.io/rev: asm-1-20
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: v1.30
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: v1.30    
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "ReservedFor", "operator": "Equal", "effect": "NoSchedule", "value": "apps"}]'