kind: ConfigMap
apiVersion: v1
metadata:
  name: payment-cm
  namespace: {{ .Values.NAMESPACES.APP }}
  labels:
    app: {{ .Chart.Name }}
    service: payment-api
data:
  Identity__Url: {{ print "https://" .Values.ISTIO.IDENTITY.EXTERNAL_URL }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"  
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.OTEL.ENDPOINT }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment-api
  namespace: {{ .Values.NAMESPACES.APP }}
  labels:
    app: {{ .Chart.Name }}
    service: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1         
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: payment-api
        azure.workload.identity/use: "true"         
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ISTIO.PAYMENT.PORT | quote }}
        prometheus.io/path: "/metrics"     
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      nodeSelector:
        App: eshop
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        supplementalGroups: [2000]
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault          
      containers:
        - name: payment-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/paymentprocessor:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.ISTIO.PAYMENT.PORT }}
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true            
            capabilities:
              drop: ["ALL"]        
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ISTIO.PAYMENT.PORT }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3    
          envFrom:
            - configMapRef:
                name: payment-cm
          env:
          - name: ConnectionStrings__eventbus
            valueFrom:
              secretKeyRef:
                name: eshop-eventbus-secrets
                key:  RABBITMQ_CONNECTION_STRING                             
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: {{ .Values.NAMESPACES.APP }}
  labels:
    app: {{ .Chart.Name }}
    service: payment-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ISTIO.PAYMENT.PORT }}
  selector:
    service: payment-api