apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
  namespace: {{ .Values.NAMESPACES.APP }}  
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}