---
{{- if .Values.DEPLOY.REDIS -}}
apiVersion: v1
kind: Secret
metadata:
  name: eshop-redis-secrets 
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  redis-connection-string: {{ print "redis." .Values.NAMESPACES.INFRA ".svc.cluster.local,user=" .Values.REDIS.USER ",password=" .Values.REDIS.PASSWORD  | b64enc }}
{{- end }}
---