---
{{- if .Values.DEPLOY.SQL -}}
apiVersion: v1
kind: Secret
metadata:
  name: eshop-sql-secrets
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  catalogdb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=catalogdb" | b64enc }}
  identitydb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=identitydb" | b64enc }}
  orderingdb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=orderingdb" | b64enc }}
  webhooksdb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=webhooksdb" | b64enc }}
{{- end }}
---