---
apiVersion: v1
kind: Secret
metadata:
  name: eshop-eventbus-secrets
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  RABBITMQ_CONNECTION_STRING: {{ print "amqp://" .Values.EVENTBUS.USER ":" .Values.EVENTBUS.PASSWORD "@eventbus." .Values.NAMESPACES.INFRA ".svc.cluster.local:" .Values.EVENTBUS.PORT | b64enc }}
---
{{- if .Values.DEPLOY.SQL -}}
apiVersion: v1
kind: Secret
metadata:
  name: eshop-sql-secrets
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  catalogdb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=catalogdb" | b64enc }}
  identitydb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=identitydb" | b64enc }}
  orderingdb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=orderingdb" | b64enc }}
  webhooksdb-connection-string: {{ print "Host=postgres." .Values.NAMESPACES.INFRA ".svc.cluster.local;Username=" .Values.POSTGRESQL.USER ";Password=" .Values.POSTGRESQL.PASSWORD ";Port=" .Values.POSTGRESQL.PORT ";Database=webhooksdb" | b64enc }}
{{- end }} 
---
{{- if .Values.DEPLOY.REDIS -}}
apiVersion: v1
kind: Secret
metadata:
  name: eshop-redis-secrets 
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  redis-connection-string: {{ print "redis." .Values.NAMESPACES.INFRA ".svc.cluster.local,user=" .Values.REDIS.USER ",password=" .Values.REDIS.PASSWORD  | b64enc }}
{{- end }} 
