---
apiVersion: v1
kind: Secret
metadata:
  name: eshop-eventbus-secrets
  namespace: {{ .Values.NAMESPACES.APP }}
type: Opaque
data:
  RABBITMQ_CONNECTION_STRING: {{ print "amqp://" .Values.EVENTBUS.USER ":" .Values.EVENTBUS.PASSWORD "@eventbus." .Values.NAMESPACES.INFRA ".svc.cluster.local:" .Values.EVENTBUS.PORT | b64enc }}
---