kind: ConfigMap
apiVersion: v1
metadata:
  name: webapp-cm
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: webapp
data:
  CallBackUrl: {{ print "https://" .Values.ISTIO.WEBAPP.EXTERNAL_URL }}
  IdentityUrl: {{ print "https://" .Values.ISTIO.IDENTITY.EXTERNAL_URL }}
  AZURE_CLIENT_ID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
  APP_INSIGHTS_CONNECTION_STRING: {{ .Values.APP_INSIGHTS.CONNECTION_STRING }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.OTEL.ENDPOINT }}
  services__basket-api__http__0: {{ .Values.ISTIO.BASKET.INTERNAL_URL }}
  services__basket-api__https__0: {{ .Values.ISTIO.BASKET.INTERNAL_URL }}
  services__ordering-api__http__0: {{ .Values.ISTIO.ORDERING.INTERNAL_URL }}
  services__ordering-api__https__0: {{ .Values.ISTIO.ORDERING.INTERNAL_URL }}
  services__catalog-api__http__0: {{ .Values.ISTIO.CATALOG.INTERNAL_URL }}    
  services__catalog-api__https__0: {{ .Values.ISTIO.CATALOG.INTERNAL_URL }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
    service: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: webapp
        azure.workload.identity/use: "true" 
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ISTIO.WEBAPP.PORT | quote }}
        prometheus.io/path: "/metrics"          
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      nodeSelector:
        App: eshop      
      containers:
        - name: webapp
          image: {{ print .Values.ACR.NAME ".azurecr.io/webapp:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.ISTIO.WEBAPP.PORT }}
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false          
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ISTIO.WEBAPP.PORT }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3     
          envFrom:
            - configMapRef:
                name: webapp-cm
          env:       
          - name: ConnectionStrings__eventbus
            valueFrom:
              secretKeyRef:
                name: eshop-eventbus-secrets
                key:  RABBITMQ_CONNECTION_STRING            
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: webapp
  namespace: {{ .Values.NAMESPACE }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ISTIO.WEBAPP.PORT }}
  selector:
    service: webapp
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  webapp-vs
  namespace: {{ .Values.NAMESPACE }}
spec:
  hosts:
  -  {{ .Values.ISTIO.WEBAPP.EXTERNAL_URL }}
  gateways:
  -  {{ .Values.ISTIO.GATEWAY }}
  http:
  - route:
    - destination:
        host: webapp
        port:
          number: 80