kind: ConfigMap
apiVersion: v1
metadata:
  name: webhooks-api-cm
  namespace: {{ .Values.NAMESPACES.APP }}
  labels:
    app: {{ .Chart.Name }}
    service: webhooks-api
data:
  AZURE_CLIENT_ID: {{ .Values.WORKLOAD_ID.CLIENT_ID }}
  Identity__Url: {{ print "https://" .Values.ISTIO.IDENTITY.EXTERNAL_URL }}
  APP_INSIGHTS_CONNECTION_STRING: {{ .Values.APP_INSIGHTS.CONNECTION_STRING }}
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  DOTNET_USE_POLLING_FILE_WATCHER: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.OTEL.ENDPOINT }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webhooks-api
  namespace: {{ .Values.NAMESPACES.APP }}
  labels:
    app: {{ .Chart.Name }}
    service: webhooks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webhooks-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1          
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        service: webhooks-api
        azure.workload.identity/use: "true" 
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.ISTIO.WEBHOOKS.PORT | quote }}
        prometheus.io/path: "/metrics"             
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      nodeSelector:
        App: eshop
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        supplementalGroups: [2000]
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault        
      containers:
        - name: webhooks-api
          image: {{ print .Values.ACR.NAME ".azurecr.io/webhooks-api:" .Values.GIT_COMMIT_VERSION }}
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.ISTIO.WEBHOOKS.PORT }}
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: "0.5"
              memory: 128Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true            
            capabilities:
              drop: ["ALL"]         
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ISTIO.WEBHOOKS.PORT }}
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3   
          envFrom:
            - configMapRef:
                name: webhooks-api-cm
          env:
          - name: ConnectionStrings__webhooksdb
            valueFrom:
              secretKeyRef:
                name: eshop-sql-secrets
                key: webhooksdb-connection-string                 
          - name: ConnectionStrings__eventbus
            valueFrom:
              secretKeyRef:
                name: eshop-eventbus-secrets
                key:  RABBITMQ_CONNECTION_STRING
{{- if .Values.DEPLOY.SQL -}}
{{- else }}                  
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"                       
            readOnly: true  
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: eshop-sql-secrets
{{- end }}                           
      tolerations:
      - key: "ReservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: webhooks-api
  namespace: {{ .Values.NAMESPACES.APP }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ISTIO.WEBHOOKS.PORT }}
  selector:
    service: webhooks-api