apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.NAMESPACES.OTEL }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.NAMESPACES.INFRA }}
  labels:
    istio.io/rev: {{ .Values.ISTIO.VERSION }}
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "ReservedFor", "operator": "Equal", "effect": "NoSchedule", "value": "apps"}]'