{{- if .Values.DEPLOY.REDIS -}}
apiVersion: v1
kind: Secret
metadata:
  name: eshop-redis-secrets 
  namespace: {{ .Values.NAMESPACES.INFRA }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.REDIS.PASSWORD | b64enc }}
stringData:
  redis.conf: |
    user {{ .Values.REDIS.USER }} on +@all ~* >{{ .Values.REDIS.PASSWORD }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.NAMESPACES.INFRA }}
  labels:
    app: {{ .Chart.Name }}
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      nodeSelector:
        App: eshop       
      containers:
      - name: redis
        image: redis:latest
        command: ["redis-server", "/etc/redis/redis.conf"]
        ports:
        - containerPort: {{ .Values.REDIS.PORT }} 
        securityContext:
          allowPrivilegeEscalation: false  
          runAsUser: 1000       
          runAsNonRoot: true
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2"
          requests:
            memory: "1024Mi"
            cpu: "0.25"
        volumeMounts:
        - name: redis
          mountPath: "/etc/redis"
          readOnly: true
      volumes:
      - name: redis
        secret:
          secretName: eshop-redis-secrets 
          items:
          - key: redis.conf
            path: redis.conf
---
kind: Service
apiVersion: v1
metadata:
  name: redis 
  namespace: {{ .Values.NAMESPACES.INFRA }}
  labels:
    app: {{ .Chart.Name }}
    service: redis 
spec:
  type: ClusterIP
  ports:
    - name: redis 
      port: {{ .Values.REDIS.PORT }}
      targetPort: {{ .Values.REDIS.PORT }}
  selector:
    service: redis 
{{- end }}  