apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: istio-tls
  namespace: aks-istio-ingress
spec:
  provider: azure
  secretObjects:                               
  - secretName: istio-ingress-tls
    type: kubernetes.io/tls
    data: 
    - objectName: wildcard-certificate
      key: tls.key
    - objectName: wildcard-certificate
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: pigeon-10408-kv
    clientID: efe54681-26b1-4782-8041-39e4e13adbc8
    cloudName: ""                                         
    objects:  |
      array:
        - |
          objectName: wildcard-certificate
          objectType: secret
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3